### ISSUE TITLE
Broken in IE 11

### ISSUE THREAD

**Issue by danransom** [swfobject/swfobject#26]
See list of changes for IE 11:

http://msdn.microsoft.com/en-us/library/ie/bg182625(v=vs.85).aspx

1. Do not use navigator.appName as IE 11 now reports "netscape"
2. Mutation Events are no longer supported.
3. attachEvent has been removed for IE 11

**Comment by JabbyPanda** [comment]
Recommended updates for SWFObject to support IE11 from Adobe engineer are listed here
http://code.google.com/p/swfobject/issues/detail?id=686

**Comment by pipwerks** [comment]
Please note, as of 2015 SWFObject is no longer in active development.
