### ISSUE TITLE
PercentLoaded Not Working With Large SWFs

### ISSUE THREAD

**Issue by MyiCo** [swfobject/swfobject#36]
Hi, i'm having problem loading large SWF with SwfObject, it works great with small to meduim size SWFs(14 Mega), but once i tried to load a 37 Mega SWF, the percentloaded() stopped working at a certain value, is there a solution for this !

**Comment by pipwerks** [comment]
This is not a SWFObject issue, this is a Flash Player issue. All SWFObject does is embed the SWF on the page, Flash Player handles the rest. Sorry, I don't have any suggestions for how to handle such a large SWF.
