### ISSUE TITLE
Proposal for a new API.

### ISSUE THREAD

**Issue by eisenlaub** [swfobject/swfobject#39]
The current API for embedding SWF is not easy to use. Some parameters are optional, others are not. Without a good IDE it's difficult to keep track how many `null` arguments must be passed before one reaches the position in the argument list for `parameters`. 

Thus I'm proposing to implement a new API for SWF embedding by utilizing the builder pattern to describe optional arguments and kicking off the actual embedding. 

Old:
```javascript
embedSWF('myContent', document.getElementById("my-target-element"), 
         '480px', '320px', '9.0.0', null, null, {AllowNetworking: 'none'});
```

New:
```javascript
swfobject.embed('myContent.swf', "480px", "320px", '9.0.0')
         .parameters({AllowNetworking: 'none'})
         .into(document.getElementById("my-target-element"));
```
Maybe the necessary arguments can also passed through the builder pattern but I guess it would be to noisy to specify height and width this way. 

What do you think?

**Comment by kirbyfan64** [comment]
+1 I like this idea.

**Comment by tensafefrogs** [comment]
Swfobject development is mostly dead these days. It's unlikely that you'll see a new realese unless there's some major change in the way swf files are embedded or we see some renewed use of the flash file format.

Flash is dead. If you really want to spend the time updating the swfobject api I suggest you fork the project and go for it, but personally I'd recommend you spend your time on something more worthwhile :)

**Comment by eisenlaub** [comment]
There are still some Use Cases left for flash. There is also an active community around it. I don't like it either but I accept it. And within this community they still create new Flash Animations which are pretty nice. 

Only because Silicon Valley wants Flash dead doesn't mean it is actually dead. Mozilla works on a Flash Runtime Environment in Javascript called Shumway. This will extend the lifetime of Flash and brings it to different platforms. Shumway mimics the API defined in this library. My long(er) term plan was to simplify the API here and then walk over to them and propose the same API again.

**Comment by pipwerks** [comment]
Your proposal is sound, but the swfobject team has pretty much moved on. We have no plans to update swfobject at this time. 

As an aside, my personal preference would be to use a configuration object:

Old: 

    swfobject.embed('myContent', document.getElementById("my-target-element"), 
            '480px', '320px', '9.0.0', null, null, {AllowNetworking: 'none'});

Your proposal:

    swfobject.embed('myContent.swf', "480px", "320px", '9.0.0')
        .parameters({AllowNetworking: 'none'})
        .into(document.getElementById("my-target-element"));

My preference:

    swfobject.embed("myContent.swf", { 
        width: "480px",
        height: "320px", 
        requires: "9.0.0",
        params: { AllowNetworking: "none" },
        flashvars: { foo: "bar" }
    }).into(document.getElementById("my-target-element"));

It may be more verbose, but it follows the convention of using an object for passing optional arguments.
