### ISSUE TITLE
swfobject 2.2 can't work in microsoft edge browser

### ISSUE THREAD

**Issue by zhangbg** [swfobject/swfobject#46]
The "swfobject 2.2" can't work in microsoft edge browser. Can anyone tell me the solution? Any help will be appreciated!

**Comment by matbury** [comment]
MS Edge doesn't support ActiveX and so doesn't support Flash Player.

**Comment by tensafefrogs** [comment]
I did a quick search and it appears to support the Flash player, but I don't know any of the technical details.

If it doesn't support ActiveX, then does it use a custom player, or does it have some sort of ActiveX runner?

**Comment by tensafefrogs** [comment]
Closing for lack of response.
