### ISSUE TITLE
No longer checks GetVariable("$version") after embedSWF is called

### ISSUE THREAD

**Issue by Melissa-Kay** [swfobject/swfobject#47]
Working off the original source. Noticed testPlayerVersion() was no longer getting called (it was getting called in an older version I had), meaning GetVariable("$version"); wasn't getting checked/stored either. This was because domLoadFnArr.length was returning 0.

Compared to old version I had, domLoadFnArr variable had function defined in the array when the var was declared at the top. Newest version has the var declaration array empty and sets domLoadFnArr[0] = function later on in the code. Renaming the domLoadFnArr[0] to checkVersion and specifying it within the domLoadFnArr array at the top fixed my issue. Not sure if this change was intended but figured I'd post just in case. 

```
@@ -19,7 +19,7 @@ var swfobject = function () {
         nav = navigator,

         plugin = false,
-           domLoadFnArr = [],
+          domLoadFnArr = [checkVersion],
         regObjArr = [],
         objIdArr = [],
         listenersArr = [],

@@ -286,16 +321,18 @@ var swfobject = function () {
     /* Main function
         - Will preferably execute onDomLoad, otherwise onload (as a fallback)
     */
-        domLoadFnArr[0] = function () {
+       function checkVersion() {
```

**Comment by ROBERT-MCDOWELL** [comment]
pleasse send a push commit thanks
