### ISSUE TITLE
Chrome swfObject create success rate of 65%

### ISSUE THREAD

**Issue by flonly2008** [swfobject/swfobject#49]
Hello I'm develop a video website, for playing rtmp video stream. According my test data.,from my flash (swf file) downloaded success to Flash Dom Object create success, I lost 35% PV. I use SwfObject(https://github.com/swfobject/swfobject) to create  Flash Object. Can you give me some suggestions to optimize it，  look forward to your reply。

 Best Regards.  
 Flonly

**Comment by suncheeze** [comment]
Hi there! Seems like we are on the same boat, have you got a chance to fix this? Please update with your current status.

Thanx

**Comment by pipwerks** [comment]
Not a SWFObject issue, and SWFObject is not in active development (please read the notice on the main page). This is open-source, you're welcome to fork and modify to suit your needs.
