### ISSUE TITLE
flashvars(stream and server) values

### ISSUE THREAD

**Issue by adeesultan** [swfobject/swfobject#55]
If i want to send source authentication mean send a stream to an rtmp server through swfobject with username and password then how to embed that with server URL or any other resource.
I am using wowza server to publishing my webcam stream, it requires source authentication and swfobject didn't carrying username and password with any thing(flashvars etc).
So, anyone know how to send username and password with swfobject (flashvars server:).

**Comment by ROBERT-MCDOWELL** [comment]
why do you want to use swfobject to broadcast a stream to the server?
makes no sense at all. Just send directly your stream to the server with your user and pass
and check if from your server application main.asc file.
Now if you want the users to play the stream pass an authentication so the best would be develop a web side like php or else script to restrict the video access.
