### ISSUE TITLE
adding flash video to webpage through SWFobject not playing in browser

### ISSUE THREAD

**Issue by billee06** [swfobject/swfobject#56]
Hi community!
I'm new to coding and trying to practice this piece of code but when I launch the code I only get the player and when I press the play button nothing appears. 
I've been at this for 3 days now and I am unsure what needs to be corrected. I'm studying html&css design and build websites by Jon Duckett and even he told me what needed to be corrected but the code isn't producing the same results as his code.
If anyone can point out a solution that would be so helpful.
the sample piece can be downloaded here http://www.htmlandcssbook.com/code-samples/
Its chapter 9 adding a flash video. If you need anything from me such as my piece of code I can post that as well.

**Comment by pipwerks** [comment]
Hello billee06

No offense, but this is a bug/issue tracking system. I suggest heading to a forum such as [StackOverflow](http://stackoverflow.com/) for assistance troubleshooting your code.

Thanks

**Comment by billee06** [comment]
Oh ok I didn't know,
Thanks for the info !

**Comment by billee06** [comment]
Hello

No one answered my question on stackoverflow?

**Comment by billee06** [comment]
Still got no answer on stackoverflow
