### ISSUE TITLE
how to allow/play sound in code?

### ISSUE THREAD

**Issue by halcheung** [swfobject/swfobject#62]
I am trying to embed a live rtmp stream in my website with SWFObject, and the video contains sound. However, when I play it, the video part works good, but without sound (I have tested before with other flash player, the sound worked perfectly). I right click the flash setting, the Sound setting part is unavailable. So I was wondering is there any switch or param to turn the sound on?

**Comment by sizco29** [comment]
The library is not longer active so you should move on to another library
