### ISSUE TITLE
Get error from player

### ISSUE THREAD

**Issue by jzr-ars** [swfobject/swfobject#64]
Hello,
I play my streaming use this, but i got some error like "Error Error#2154" etc.
Can i get the error status with my js file which create this swfobject ?

**Comment by SuperOP535** [comment]
- [x] Project died 3 days ago
- [x] Flash is going to die in some years
- [x] Question is most likely not going to be answered

**Comment by christiankremser** [comment]
you have to communicate with flash and swfobject: http://learnswfobject.com/advanced-topics/external-interface/

**Comment by ROBERT-MCDOWELL** [comment]
flash will never die, it will mutate for sure but never die...
